# Generated by Django 2.1.5 on 2021-01-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210126_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Description',
        ),
    ]
